#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "---> ACTION HOOK: deploy <---"
source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

# Set WSGI entry point
export OPENSHIFT_PYTHON_WSGI_APPLICATION=${OPENSHIFT_REPO_DIR}/carpool_news/carpool_news/wsgi.py

echo "Executing 'python $OPENSHIFT_REPO_DIR/carpool_news/manage.py migrate --noinput'"
python "$OPENSHIFT_REPO_DIR"/carpool_news/manage.py migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/carpool_news/manage.py bower_install'"
python "$OPENSHIFT_REPO_DIR"/carpool_news/manage.py bower_install

echo "Executing 'python $OPENSHIFT_REPO_DIR/carpool_news/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"/carpool_news/manage.py collectstatic --noinput